# Generated by Django 4.1.3 on 2022-11-12 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='codregistro',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AddField(
            model_name='user',
            name='date_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Nciemiento: '),
        ),
        migrations.AddField(
            model_name='user',
            name='ocupation',
            field=models.CharField(blank=True, max_length=30, verbose_name='Ocupación'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
